### ISSUE TITLE
Unable to render table

### ISSUE THREAD

**Issue by Pathsis** [alexcarpenter/nextjs-mdx-blog-theme#4]
hi, alexcarpenter!

Thank you for developing this next.js theme, it's the best next.js theme I could find, I think it's promising and needs further improvement to be a great theme.

The immediate problem now is that it is not possible to render the table.

<img width="828" alt="截屏2023-03-08 01 19 02" src="https://user-images.githubusercontent.com/72077265/223499780-757f20d2-90e4-4ee2-b30e-cab3716d2cbf.png">

**Comment by alexcarpenter** [comment]
Fixed here https://github.com/alexcarpenter/nextjs-mdx-blog-theme/pull/5
